/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "push_button_aliases.h"
#include "push_button.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "DMA_I2C_dma.h"
#include "DMA_SPI_dma.h"
#include "I2C_INTR_aliases.h"
#include "I2C_INTR.h"
#include "I2C_DataReady.h"
#include "Timer_1.h"
#include "Timer_ISR.h"
#include "PWM2.h"
#include "Pin_Red_Led_1_aliases.h"
#include "Pin_Red_Led_1.h"
#include "Pin_Blue_Led_1_aliases.h"
#include "Pin_Blue_Led_1.h"
#include "Pin_Green_Led_1_aliases.h"
#include "Pin_Green_Led_1.h"
#include "PWM1.h"
#include "Zeit.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

